name: Security Scan

on:
  pull_request:
    branches: [ develop, main ]
  schedule:
    - cron: '0 2 * * 1'  # Tous les lundis à 2h

jobs:
  security-scan:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    # Snyk Security Scan
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/maven@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high --file=pom.xml

    - name: Upload Snyk results to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: snyk.sarif

    - name: Upload Snyk report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: snyk-vulnerability-report
        path: snyk.sarif

    # CodeQL seulement sur le scan programmé (pas sur les PR)
    - name: Initialize CodeQL
      if: github.event_name == 'schedule'
      uses: github/codeql-action/init@v3
      with:
        languages: java

    - name: Build for CodeQL
      if: github.event_name == 'schedule'
      run: ./mvnw clean compile -DskipTests

    - name: Perform CodeQL Analysis
      if: github.event_name == 'schedule'
      uses: github/codeql-action/analyze@v3
